version: '3.8'

services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"      # client
      - "9093:9093"      # controller
    environment:
      # Enable KRaft mode (no ZooKeeper) :contentReference[oaicite:2]{index=2}
      KAFKA_KRAFT_MODE: "true"
      # This node is both broker and controller :contentReference[oaicite:3]{index=3}
      KAFKA_PROCESS_ROLES: "broker,controller"
      # Unique ID for this Kafka node
      KAFKA_NODE_ID: "1"
      # Controller quorum voters list (nodeId@hostname:port) :contentReference[oaicite:4]{index=4}
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # Network listeners for clients and controller
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      # What clients should use to connect
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      # Store data locally
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # Single‑node replication settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8092:8080"
    environment:
      # Define the cluster for the UI to manage :contentReference[oaicite:5]{index=5}
      KAFKA_CLUSTERS_0_NAME: "local-kraft"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

volumes:
  kafka-data:
