server:
  port: 8086
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1
        - id: apartment-service
          uri: lb://apartment-service
          predicates:
            - Path=/apartment/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html   # swagger будет доступен по http://localhost:8086/swagger-ui.html
#
#    urls:
#      - name: user-service
#        url: /user/v3/api-docs
#      - name: booking-service
#        url: /booking/v3/api-docs
#      - name: apartment-service
#        url: /apartment/v3/api-docs
#      - name: payment-service
#        url: /payment/v3/api-docs

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0