server:
  port: 8086
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888