spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5435/booking_service_db
    username: postgres
    password: Nadi.3344

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
