spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5438/payment_service_db
    username: postgres
    password: Nadi.3344

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8085
