spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5436/review_service_db
    username: postgres
    password: Nadi.3344

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8084
