

spring:
  application:
    name: apartment-service

  datasource:
    url: jdbc:postgresql://localhost:5434/apartment_service_db
    username: postgres
    password: Nadi.3344
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
