spring:
  application:
    name: apartment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/apartment_service_db
    username: postgres
    password: Nadi.3344
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8089/realms/qonys
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: apartment-service
            client-secret: qCIHhSmdmuX1RCLxxBSSFBCBssoToo2D
            scope:
              - openid
              - microprofile-jwt


eureka:
  instance:
    prefer-ip-address: true
  client:
  service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

keycloak:
  uri: http://localhost:8089

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0